[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "mazegen"
version = "1.0.1"
description = "Un generador de laberintos perfecto y loops reutilizable para 42"
readme = "README.md"
requires-python = ">=3.10"
authors = [
    {name = "Maria Gabriela Reyes Mosquera", email = "mreyes-m@student.42barcelona.com"},
    {name = "Ignacio López Gómez", email = "ilopez-g@student.42barcelona.com"}
]
classifiers = [
    "Programming Language :: Python :: 3",
]
license-files = ["LICEN[CS]E*"]

[tool.setuptools.packages.find]
where = ["."]
include = ["mazegen*"]